spring.application.name=ss6
spring.datasource.url=jdbc:mysql://localhost:3306/ss6_db
spring.datasource.username=root
spring.datasource.password=Qazxsw2006@

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
